import Head from 'next/head'
import React from 'react'
import SideBarComponent from './SideBarComponent'
import HeaderComponent from './HeaderComponent'
import { ToastContainer } from 'react-toast'
type Props = {
  title: string,
  children?: React.ReactElement | string | string[] | JSX.Element | React.ReactNode
}

function Layout({ title, children }: Props) {
 
  return (
    <>
      <Head>
        <title>{title ? title : 'Next App'}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ToastContainer position='bottom-center' delay={1} />
      <div className='grid-container'>
        <HeaderComponent />
        <SideBarComponent  />
        <main>
          {children}
        </main>
        <footer>Footer</footer>
      </div>
    </>
  )
}

export default Layout